### PR TITLE
made site more responsive

### PR DESCRIPTION
**Pull request by wre9-tesh**
## What does this PR do?

Fixes responsiveness ,add favicon .

## Screenshots of changes made to the webapp.

image
image

### CODE REVIEW

**Comment by Aatmaj-Zephyr** [comment]
Is the home screen of desktop layout unchanged?
I hope so because it is good as now for desktop and mobile and iPad versions need changes.

**Review by Aatmaj-Zephyr — CHANGES_REQUESTED** [review]
Thanks a lot for these changes.
Can you please update readme file by adding relevant features added and screenshots?

**Comment by wre9-tesh** [comment]
Yes the desktop layout is unchanged . I will make those changes ASAP

**Review by Aatmaj-Zephyr — APPROVED** [review]

**Comment by Aatmaj-Zephyr** [comment]
@wre9-tesh 
image

**Comment by wre9-tesh** [comment]
This was due to last pr merged not mine .but I can fix it

**Comment by Aatmaj-Zephyr** [comment]
Sure thanks for the advise. It will be really helpful if you can fix it

**Comment by wre9-tesh** [comment]
sry I couldnt  fix this issue due to my exams .I am free now and now working on the responsive issue ,i'll pull a pr in few days

**Comment by Aatmaj-Zephyr** [comment]
sure Thanks

**Pull request merged**
