### PR TITLE
added a link to the repo

### PR DESCRIPTION
**Pull request by robin6717**
## What does this PR do?

I added a link to  the repository on  the main page of the game.

## Screenshots of changes made to the webapp.

added_repo_link

## Related PRs and Issues

this is to solve the issue where a link was requested.

### Have you updated the README.md file?

- [ ] yes
- [ x] no

### Have you made any big breakthrough change?

- [ ] yes
- [ x] no

### Is the code beautified?

- [ ] yes

- [ x] no

### Is the code clear to understand woth proper variable naming and comments?

- [x ] yes
- [ ] no

### CODE REVIEW

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Please update the readme file

**Comment by robin6717** [comment]
I am sorry to ask but I am new to open source. What exactly should i update to the readme file?
And should I cancel my PR and then first add changes to the readme before I make the PR?

thank you, this is a great learning experience for me.


________________________________
Van: Aatmaj ***@***.***>
Verzonden: dinsdag 25 oktober 2022 12:54
Aan: Aatmaj-Zephyr/Hangman ***@***.***>
CC: Robin van Steenbergen ***@***.***>; State change ***@***.***>
Onderwerp: Re: [Aatmaj-Zephyr/Hangman] added a link to the repo (PR #234)


@Aatmaj-Zephyr commented on this pull request.

Please update the readme file

**Comment by robin6717** [comment]
do you mean add a screenshot of my solution to the readme file? i will look up how to do this properly. I had added a screenshot in the PR request text but i now understand that i should have done that in the readme. Am i right?
________________________________
Van: Aatmaj ***@***.***>
Verzonden: dinsdag 25 oktober 2022 12:54
Aan: Aatmaj-Zephyr/Hangman ***@***.***>
CC: Robin van Steenbergen ***@***.***>; State change ***@***.***>
Onderwerp: Re: [Aatmaj-Zephyr/Hangman] added a link to the repo (PR #234)


@Aatmaj-Zephyr commented on this pull request.

Please update the readme file

**Comment by Aatmaj-Zephyr** [comment]
Add screenshot to readme

**Pull request closed without merging**
