### PR TITLE
changed background image from repeating to a single full image

### PR DESCRIPTION
**Pull request by KrystalJean**
Thank you @Aatmaj-Zephyr for assigning this to me.  Let me know if this looks good, or if I need to make any additional changes.
Really cool game btw. 
( Fix for issue #131 )

### CODE REVIEW

**Comment by Aatmaj-Zephyr** [comment]
Can you please share screenshots of the working website after your changes?

**Comment by KrystalJean** [comment]
Sure - here is a desktop view...
poke-hangman-desktop

and here is a mobile view...
poke-hangman-mobile

**Comment by Aatmaj-Zephyr** [comment]
Thanks for the changes

**Review by Aatmaj-Zephyr — APPROVED** [review]
Approved

**Pull request merged**
